### ISSUE TITLE
Metrics server fails to install on DigitalOcean

### ISSUE THREAD

**Issue by braunsonm** [cloudfoundry/cf-for-k8s#498] opened 2020-10-01 20:30 UTC
## Describe the bug
On a fresh DigitalOcean Kubernetes server installing CF with the metrics server option fails. Even though DO does not provide the metrics server. This seemed to have worked fine before..

## To Reproduce*
1. Follow the deployment steps and set the metrics server component to true
2. Deploy

You will get an error: https://gist.github.com/braunsonm/d96c5873365f66f8fb73f8233484e162

## Expected behavior
The CF cluster should have been deployed

### Cluster information
Kubernetes on DigitalOcean

### CLI versions

1. `ytt --version`: ytt version 0.30.0
2. `kapp --version`: kapp version 0.34.0

Succeeded

3. `kubectl version`: Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

4. `cf version`: cf version 7.1.0+4c3168f9a.2020-09-09

**Comment by JamesClonk** [comment] 2020-10-02 17:24
@braunsonm Are you sure the DO K8s cluster does not already have metrics-server installed? The error message at the end of your log output does seem to indicate it already exists in `kube-system` namespace.

**Comment by braunsonm** [comment] 2020-10-02 17:33
It definitely does not come with one which makes the error even weirder. It is an optional add on in their one click apps marketplace: https://marketplace.digitalocean.com/apps/kubernetes-metrics-server

**Comment by davewalter** [comment] 2020-10-08 18:28
@braunsonm [Lines 299-302](https://gist.github.com/braunsonm/d96c5873365f66f8fb73f8233484e162#file-gistfile1-txt-L299-L302) from your gist show that kapp is detecting it as an `update`, as opposed to a `create`:

```
...
kube-system           metrics-server                                                       Deployment                      2/2 t   3m   update  -       reconcile  ok  -  
^                     metrics-server                                                       Service                         -       3m   update  -       reconcile  ok  -  
^                     metrics-server                                                       ServiceAccount                  -       3m   update  -       reconcile  ok  -  
^                     metrics-server-auth-reader                                           RoleBinding                     -       3m   update  -       reconcile  ok  -  
...
```

This also seems to imply that `metrics-server` was already installed. Unfortunately, we do not have any way to reproduce this issue. Could you please verify with a new cluster that you have confirmed does not already have the `metrics-server` deployed?

**Comment by braunsonm** [comment] 2020-10-14 02:22
Yes as I said above it does not create a metrics server. However it uses `kube-system` namespace for other pods so perhaps the config is getting confused. Here is a deployment output from a vanilla cluster:
![](https://i.imgur.com/SwO5SIW.png)

**Comment by acosta11** [comment] 2020-10-14 22:52
Hey @braunsonm,

Thanks for the update; we're sorry to hear this still isn't working for you.

After taking another look, it really looks like there was already some version/traces of a metrics-server on your cluster. We'd recommend
1) inspecting your fresh cluster with `kubectl` and checking for signs of a metrics-server (we'd be interested in seeing the results from `kubectl get pods -A`)
2) trying to install cf-for-k8s with the "enable metrics-server" set to false, and trying to deploy and run smoke tests. If there's no metrics-server, we expect the `cf push` within smoke tests to fail.

At this point, we're going to close the issue because we're not able to officially support Digital Ocean at this time. But please post updates here from our recommendations above.

Best,
Andrew and @jamespollard8

**Closed by acosta11** 2020-10-14 22:52 UTC
Labels: unscheduled
