### ISSUE TITLE
Smoke Tests should use a `cloudfoundry`  org image to avoid rate limiting

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cf-for-k8s#589] opened 2020-12-03 21:42 UTC
## Describe the bug
The smoke tests are currently using the `cfrouting/httpbin` container image for the Docker portion and this eventually hits rate limits since it is not part of the `cloudfoundry` DockerHub org

The relevant lines are here:
https://github.com/cloudfoundry/cf-for-k8s/blob/10673d5cc9017f43c7ed87bf0c75b83ac6f21dbf/tests/smoke/smoke_test.go#L115

**Comment by jamespollard8** [comment] 2020-12-17 22:41
Closing as a duplicate of https://github.com/cloudfoundry/cf-for-k8s/issues/580

**Closed by jamespollard8** 2020-12-17 22:41 UTC
Labels: unscheduled
