### ISSUE TITLE
cf push fails with "Error staging application: Staging time expired: staging failed"

### ISSUE THREAD

**Issue by kramerul** [cloudfoundry/cf-for-k8s#140] opened 2020-04-14 13:22 UTC
When running `cf push` with the application provided in [smoke tests](https://github.com/cloudfoundry/cf-for-k8s/tree/master/tests/smoke/assets/test-node-app) it fails sometimes with the error message

```
Error staging application: Staging time expired: staging failed
```

It seems that kpack is working correctly. The CR `build.build.pivotal.io` changed the state in `SUCCEEDED` to `True` after a few minutes. The image is also available on the docker registry. And it's also possible to start that image directly by `cf push -o <generated image>`.

In this case no pod is started in namespace `cf-workloads` and the related pod in `cf-workloads-staging` is in state `Completed`. 

We noticed after ~30 minutes the app seems to be started. We haven't found out which controller is responsible for this behaviour.

We also have never seen this behaviour directly after installing cf-for-k8s. We are running the smoke tests directly after the installation and they always succeed.

**Comment by kramerul** [comment] 2020-04-15 05:45
Seems to be related to https://cloudfoundry.slack.com/archives/CH9LF6V1P/p1586818920316400

**Comment by Birdrock** [comment] 2020-04-15 22:36
@kramerul - Thank you! There is a bunch of helpful context in the slack thread.

The current hypothesis is that it is an interplay between no enabling the `diego_docker` flag and using the cf7 cli. The cf6 cli has been updated to work without the `diego_docker` flag, but there are still remaining updates for cf7.

The story for capi can be found here: https://www.pivotaltracker.com/n/projects/966314/stories/172268950

**Comment by stoyanr** [comment] 2020-04-16 08:55
@Birdrock @kramerul Some more findings from our side on this issue. We enabled `diego_docker` and we only use the cf6 CLI (version 6.51.0). Nevertheless, we quite frequently observe the behavior described above - even after the app has been successfully staged, all builds / images are succeeded / ready, and the image is present in the docker registry, the app doesn't start for some time, and this time is different every time and varies between 5 to more than 30 minutes.
* Without `diego_docker`, the app never starts - only the service is created in `cf-workloads`, but not the statefulset.
* With `diego_docker`, the app starts eventually, but it could quite some time until it does, and until that moment, nothing is created in cf-workloads, even the service is missing.

**Comment by stoyanr** [comment] 2020-04-16 09:17
I also tried with cf7 CLI (version 7.0.0-beta.30), the described behavior is reproducible with it as well.

**Comment by kramerul** [comment] 2020-04-16 14:15
Hi @Birdrock,

we tried it again with the newest version of cf-for-k8s (commit 20166cdc60f7fb8df2227edc062adc461b56b827) and found out that the problem still exists **but only after waiting for 1 hour**.
Running `cf push` directly after the installation of `cf-for-k8s` was 2 times successful. Retrying it after one hour was 2 times **not** successful.
We always used the following commands:

```
cf push test -p  cf-for-k8s/tests/smoke/assets/test-node-app/
cf delete test
```

**Comment by c0d1ngm0nk3y** [comment] 2020-04-20 06:37
> The current hypothesis is that it is an interplay between no enabling the `diego_docker` flag and using the cf7 cli. 

```bash
$ cf version
cf version 6.51.0+2acd15650.2020-04-07
```

**Comment by kramerul** [comment] 2020-04-20 13:07
Hi @Birdrock, hi @XanderStrike,

we have a few interesting findings on this issue:
1. It seems that this issue is happening on AWS with a higher probability.
2. It seems that the sidecar of the `capi-kpack-watcher` is involved. After setting the annotation `traffic.sidecar.istio.io/excludeOutboundIPRanges` to `100.64.0.1/32`(IP address of the K8s API server)  everything worked fine.

**Comment by davewalter** [comment] 2020-04-21 00:35
Hi @kramerul,

Thanks for the update. To see if we could reproduce this, we deployed on both kind and GKE clusters, ran smoke-tests immediately, left the deployments for over an hour, then ran smoke-tests again. Unfortunately, we didn't see any of the issues you have described. This seems to narrow the problem down to either AWS, or your specific cluster.

We'll defer to the CAPI and Networking teams about the effectiveness of the istio sidecar annotation.

Regards,
Dave and @jamespollard8

**Comment by kramerul** [comment] 2020-04-21 15:02
Related to https://github.com/cloudfoundry/capi-k8s-release/issues/28 and https://github.com/cloudfoundry/capi-k8s-release/issues/27

**Comment by aashah** [comment] 2020-05-04 17:52
Could you share whether smoke tests have been more stable in the last week or so?

We discovered a bug related to `diego_docker` and this observation of "seeing the app eventually come up 5-30 minutes later" (more notes here - https://www.pivotaltracker.com/story/show/171830993/comments/213176137).

I'm not sure I have any comments on the `traffic.sidecar.istio.io/excludeOutboundIPRanges` update.

**Comment by kramerul** [comment] 2020-05-05 05:22
Hi @aashah,

after adding the `traffic.sidecar.istio.io/excludeOutboundIPRanges`  annotation, we no longer had problems to push applications. Therefore, we run our tests currently only with this annotation.

Before adding this annotation, the problem occurred almost every time on AWS.

In my point of view it would be in general a good idea to bypass istio when calling the kubernetes API server.

Since the `traffic.sidecar.istio.io/excludeOutboundIPRanges`  annotation reduced the failure rate to zero, I would expect that the error is related to istio. Since watching k8s resources is based on long running HTTP requests (websockets) I would expect that these connections are closed from time to time by envoy. We had a look at the `kpack-watcher` code and found no place where such a case (reconnect) is handled.

As you can see in [my comment](https://github.com/cloudfoundry/capi-k8s-release/issues/28#issuecomment-617247603), I would also consider switching to the controller runtime.

**Comment by kramerul** [comment] 2020-05-05 07:26
Hi @aashah,

we will test it again without the annotation. But this will take some time.

**Comment by kramerul** [comment] 2020-05-05 12:05
I tested it today with commit 21209bbfcadf626a81bc19a8320050b98076f25e and the bug is still there!

Now, we are also able to see the build log. After the statement `Build successful` it takes some minutes until the deployment fails.

```
   Configuring environment
   NPM_CONFIG_LOGLEVEL   -> error
   NPM_CONFIG_PRODUCTION -> true
   PATH                  -> $PATH:/layers/org.cloudfoundry.npm/modules/node_modules/.bin
   Adding layer 'launcher'
   Adding layer 'org.cloudfoundry.node-engine:node'
   Adding layer 'org.cloudfoundry.npm:modules'
   Adding 1/1 app layer(s)
   Adding layer 'config'
   *** Images (sha256:a76f66d5fd3cdfd1aa5128cc8ebc95148e962e1c552fdb7ae45f3c9cd38edda5):
   gcr.io/sap-se-gcp-istio-dev/cf-workloads/eb6c1b89-0a63-49f4-9bf0-d4ddaec1bf55
   gcr.io/sap-se-gcp-istio-dev/cf-workloads/eb6c1b89-0a63-49f4-9bf0-d4ddaec1bf55:b1.20200505.115741
   Adding cache layer 'org.cloudfoundry.node-engine:node'
   Adding cache layer 'org.cloudfoundry.npm:npm-cache'
   Build successful
Error staging application: Staging time expired: staging failed
FAILED
```

**Comment by kramerul** [comment] 2020-05-05 12:06
If you are interested in analyzing this issue, I think it should be no problem to grant you access to our cluster.

**Comment by kramerul** [comment] 2020-05-07 05:39
Hi @aashah,
I have sent you the credentials in slack.

**Comment by aashah** [comment] 2020-05-11 18:10
I looked over the environment that Ulrich provided with Jwal. Ulrich recommended reproducing the error by pushing the test-node-app. We easily reproduced the error. The most interesting piece of this was that the capi-kpack-watcher appeared to be in some kind of 'zombie' state. We found some logs from the sidecar that don't look like healthy logs, and think that is related.

My timeline of operations:

[16:36]:
  * pushed test-node-app, staging failued
  * build succeeded (visible through k9s and `k get builds -A`)
[16:36-17:05]
  * capi-kpack-watcher logs were unretrievable
  * istio-proxy showed some envoy logs that looked suspicious [1]
[17:06]
  * capi-kpack-watcher _suddenly_ comes back online
  * processes build object created at 16:36
  * app comes up
  * all healthy logs from this moment in time

* Regarding the capi-kpack-watcher, it’s unclear why we were not able to retrieve
any logs, nor why it “suddenly” comes up.

* We agree with your hunch being a networking/sidecar issue. We can see requests[1] whose duration (“3600000") seems to be hitting some kind of timeout (compared to a healthy one whose duration is “36”).

Followup question: have you explored whether firewall rules / calico configurations are preventing the requests from hitting the API server? I’m not personally too knowledgable about calico configurations, and I can see a lot of calico NetworkPolicy’s. I personally don't know much more to debug the networking part of this, would be nice to bring in someone from networking team.

[1] Egress request from capi-kpack-watcher to the k8s-api-server -
```
{"process_type":"-","x_b3_parentspanid":"-","space_id":"-","user_agent":"-","start_time":"2020-05-08T15:06:01.139Z","method":"-","request_id":"-","upstream_host":"<ip>:443","x_forwarded_for":"-","referer":"-","bytes_sent":"2004","response_duration":"-","upstream_cluster":"outbound|443||kubernetes.default.svc.cluster.local","x_b3_traceid":"-","downstream_remote_address":"<ip>:45302","x_forwarded_proto":"-","authority":"-","path":"-","protocol":"-","upstream_service_time":"-","upstream_local_address":"<k8s-api-server>:36716","duration":"3600007","downstream_local_address":"<k8s-api-server>:443","upstream_transport_failure_reason":"-","response_code":"0","response_flags":"-","response_tx_duration":"-","requested_server_name":"-","bytes_received":"1671","organization_id":"-","app_id":"-","x_b3_spanid":"-"}```

**Comment by kramerul** [comment] 2020-05-12 05:06
I don't think that firewall rules/calico configurations are preventing the requests from hitting the API server. If you put the annotation on the `capi-kpack-watcher`
```
traffic.sidecar.istio.io/excludeOutboundIPRanges: '100.64.0.1/32'
```
everything works fine.

If it is really caused by the network policy, it is the 3rd bug we have found that is due to it. And you should turn on network policies in your tests as soon as possible.

**Comment by tcdowney** [comment] 2020-05-14 21:01
@kramerul 

Our team (CF Networking) is investigating this [on this story](https://www.pivotaltracker.com/story/show/172809138). We worked a bit with @aashah on the EKS environment you had provided and came away with a few findings (but no answers) which we recorded on that story. I'll paraphrase them here in case they spark ideas:

```
We see Keep Alives from the client to the K8s API without the sidecar, but not with the sidecar. Why?

We see TCP Dup Ack from the sidecar to the client when the issue occurs on EKS. Why?

We see Fin, Ack on our GKE Environment when the watch connection ends from the client to the server (through the sidecar), but not on EKS. Why?
```

It looks like the EKS env has gone away though. Is there anyway you could provide us with another one @kramerul or describe how it was deployed?

cc @ndhanushkodi @christianang @jrussett

**Comment by kramerul** [comment] 2020-05-15 04:28
@tcdowney,

I will create a new cluster and send you the credentials in slack.

**Comment by kramerul** [comment] 2020-05-15 06:34
@tcdowney, I created a new cluster and sent you the credentials via slack.

**Comment by christianang** [comment] 2020-05-15 22:15
So we currently have a theory that TCP keepalives are part of the problem. AWS Elastic Load Balancers have a [non configurable idle timeout](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/network-load-balancers.html#connection-idle-timeout) of 350 seconds. The idle timeout can be reset by a TCP Keepalive packet. Envoy in Istio 1.4 currently does not do TCP Keepalives and there isn't a way to configure it. It is available and configurable in Istio 1.5.

We attempted to recreate in-place the istio deployment on your cluster, but ran into various issues. Also your cf dns wasn't configured, which also caused problems. I think it might be easier to redeploy with Istio 1.5 using our branch https://github.com/cloudfoundry/cf-k8s-networking/tree/istio-1.5-keepalive to test this.

To update your `cf-for-k8s` to use this branch you can change the `ref` for `cf-k8s-networking` in the `vendir.yml` to the commit sha of that branch: `57015b471b9d6eae914b15ffe2a6c3a0b37d1e73`. Then you can run `vendir sync` and continue with the installation as normal.

**Comment by kramerul** [comment] 2020-05-19 05:22
After switching to the branch I get

```
$ cf push test
Pushing app test to org test / space test as admin...
Getting app info...
Updating app with these attributes...
  name:                test
  path:                /Users/d001323/workspace/cf-for-k8s/tests/smoke/assets/test-node-app
  disk quota:          1G
  health check type:   port
  instances:           1
  memory:              1G
  stack:               cflinuxfs3
  routes:
    test.cf.uli.istio.shoot.canary.k8s-hana.ondemand.com

Updating app test...
Mapping routes...
Comparing local files to remote cache...
Packaging files to upload...
Uploading files...
 829 B / 829 B [=================================================================] 100.00% 1s

Waiting for API to complete processing files...

Stopping app...

Staging app and tracing logs...
   prepare:main.go:97: Get http://cf-blobstore-minio.cf-blobstore.svc.cluster.local:9000/cc-packages/6d/01/6d013f12-de42-4d53-801f-e1f4d9a62160?AWSAccessKeyId=admin&Signature=ACjvAewJx/Nw5JgsVaXn57lWZus%3D&Expires=1589868669: read tcp 100.96.2.14:56710->100.70.63.60:9000: read: connection reset by peer
Error staging application: Stager error: Kpack build failed. build failure message: ''. err: 'the server could not find the requested resource (get pods 480da3bb-7992-4e20-a973-2540919f55d7-build-2-p7glx-build-pod)'
FAILED
```

**Comment by jrussett** [comment] 2020-05-19 17:16
@kramerul could you please provide credentials for a `cf-for-k8s` environment with the `istio-1.5-keepalive` branch installed? We don't have gardener style environments and it's difficult for us to procure one.

**Comment by kramerul** [comment] 2020-05-20 06:26
I sent you the credentials on slack. I will keep the cluster running. Please tell me if you don't need it anymore.

**Comment by jrussett** [comment] 2020-05-20 23:59
Hey @kramerul, thanks for providing the environment! We took a look at the issue today but found nothing conclusive. Will continue to investigate tomorrow.

**Comment by kauana** [comment] 2020-05-21 18:01
Hello @kramerul we are taking a look at the cluster you provided us today. 

I noticed you mentioned that when you add the `traffic.sidecar.istio.io/excludeOutboundIPRanges: '100.64.0.1/32'` property to `cf-api-kpack-watcher` everything works fine. But we just checked the `cf-api-kpack-watcher` deployment and that annotation is still there, yet we cannot push buildpack applications. 

Were you previously able to push this application with that annotation before on this new cluster? What about the old cluster you had?

Thank you.

cc: @KauzClay

**Comment by kauana** [comment] 2020-05-22 22:06
Hello @kramerul,

We recently learned that istio 1.5 is replacing the Policy API with [Peer authentication API](https://istio.io/docs/reference/config/security/peer_authentication/). So back to Istio 1.4 Kpack applied [this Policy](https://github.com/cloudfoundry/cf-for-k8s/blob/c6039e01438584adbbffd74daadbc11ddcb6d205/config/kpack.yml) to ensure that init containers could talk to the blobstore so when we upgraded to 1.5 that policy doesn't seem to work anymore.

We then created a new PeerAuthentication object that allows the `prepare` init container that was failing to talk to the blobstore again.
```
apiVersion: security.istio.io/v1beta1                                                                                        
kind: PeerAuthentication                                                                                                     
metadata:                                                                                                                    
  name: "cf-blobstore-peer-authentication"                                                                                   
  namespace: "cf-blobstore"                                                                                                  
spec:                                                                                                                        
  selector:                                                                                                                  
    matchLabels:                                                                                                             
      app: minio                                                                                                             
  mtls:                                                                                                                      
    mode: PERMISSIVE 
```

We are encountering a new kpack error but we are talking to the kpack team in case they have seem this before. [Slack thread](https://cloudfoundry.slack.com/archives/CUWG5TXB5/p1590182902074300).

cc: @ndhanushkodi

**Comment by kramerul** [comment] 2020-05-25 05:09
Hi @jrussett, @kauana,

do you still need the cluster?

**Comment by kramerul** [comment] 2020-05-26 07:14
Hi @jrussett, @kauana,

I deleted the cluster. Please let me know if you need it again.

**Comment by ndhanushkodi** [comment] 2020-05-26 17:09
@kramerul we have time again this week to look at the issue and want to investigate the kpack issues further. Can you let us know if you can get the cluster up again and send us the credentials?

**Comment by kramerul** [comment] 2020-05-27 13:38
Hi @ndhanushkodi,

I sent you the kubeconfig on slack. I only created an empty cluster. I'm sure you are able to deploy cf-for-k8s with your changes.

I will delete the cluster again tomorrow unless you explicitly say that you still need it.

**Comment by XanderStrike** [comment] 2020-05-28 21:41
Thanks for all your help in narrowing down the cause of this issue. We're pretty sure at this point that the upgrade to 1.5 will expose the appropriate setting to resolve this issue. As such, we're going to temporarily de-prioritize the issue until we've completed and released the 1.5 upgrade. [Here is the 1.5 upgrade story](https://www.pivotaltracker.com/story/show/172031795). 

Of course, since it's still an issue, we will be leaving this issue open until we've played [the story](https://www.pivotaltracker.com/story/show/172809138) and pushed a resolution to the issue. Let us know if anything new comes to light in the mean time. Thanks for your patience!

**Comment by mike1808** [comment] 2020-08-13 23:55
Hi @kramerul . We upgrade Istio version to 1.6 and enabled TCP keepalive on sidecars. Can you please [tcpkeepalive-bugfix](https://github.com/cloudfoundry/cf-for-k8s/tree/tcpkeepalive-bugfix) branch and verify that it's working? Thanks!

**Comment by kramerul** [comment] 2020-08-14 07:01
I will be on vacation for the next 3 weeks. Hopefully one my colleagues (@phil9909, @loewenstein) will find time to try this out.

**Comment by phil9909** [comment] 2020-08-14 16:53
I just tried, but the `NetworkPolicies` are completely broken. I made some manual changes, but it still does not work and I can't tell whether it is caused by the `NetworkPolicies` or has something to do with this bug.

Will try to rebase the tcpkeepalive-bugfix branch on Monday, but now it's time for weekend.

**Comment by KauzClay** [comment] 2020-08-14 17:03
Hey @phil9909 , I was working with @mike1808 when we sent you that branch the other day. I do know that the team ran into issues with network policies, I think after istio1.5 they were replaced with `kind: PeerAuthentication`. I was under the impression we had made the appropriate changes on our side, but maybe that isn't true. Is the broken network policy stuff from your config, or from our branch?

Either way, we can find out more on Monday. Enjoy your weekend 😄

**Comment by phil9909** [comment] 2020-08-17 13:49
I could finally get it running. I set up a concourse job, which tries to `cf push` every 15-minutes. Results are mixed:
![image](https://user-images.githubusercontent.com/24714828/90402168-56dd7f80-e09f-11ea-8a4b-e4bb4c10e267.png)

I will now reapply our overlay
```yaml
#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.or_op(overlay.subset({"kind":"Deployment", "metadata":{"namespace": "cf-system", "name":"cf-api-controllers"}}), overlay.subset({"kind":"Deployment", "metadata":{"namespace": "cf-system", "name":"routecontroller"}})), expects=2
---
spec:
  template:
    metadata:
      #@overlay/merge
      #@overlay/match missing_ok=True
      annotations:
        #@overlay/match missing_ok=True
        traffic.sidecar.istio.io/excludeOutboundIPRanges: #@ data.values.gardener.apiServerIP + '/32'
```
To see if it still fixes the problem and to be sure that the push issues are not caused by something else.

Off-topic: I could figure out why the network-policies are not working for us. It is specific to our setup (the `kube-dns` service in the `kube-system` namespace has port `53` open, but the pod listens on `8053` and it seems like the network-policies are only applied after this port-mapping has happened). For now I created an overlay that fixes the problem for us. If such a setup is more common we should probably find a way to fix it upstream. Reach out to me via Slack if your interested in more details.

**Comment by phil9909** [comment] 2020-08-17 16:04
Our fix still works:
![image](https://user-images.githubusercontent.com/24714828/90417389-eab94680-e0b3-11ea-9efc-eb72d044372f.png)

Will keep it running over night.

**Comment by kauana** [comment] 2020-08-18 22:09
Cool @phil9909 thanks for letting us know :tada:. Can we close this issue? Thanks

**Comment by phil9909** [comment] 2020-08-18 23:06
@kauana Sorry, [my comment](https://github.com/cloudfoundry/cf-for-k8s/issues/140#issuecomment-674968142) was a bit misleading: With "fix" I meant the workaround with the `traffic.sidecar.istio.io/excludeOutboundIPRanges` annotation, which basically disables istio for connections to the API server.

Without that workaround it's still broken (see [my earlier comment](https://github.com/cloudfoundry/cf-for-k8s/issues/140#issuecomment-674893354))

**Comment by kauana** [comment] 2020-09-09 21:08
Hello @phil9909, 

We would like to take a look at the issues you've encountered, but we don't have an easy way of reproducing your environment config. Could you please share a cluster with us so we can take a better look at the issues you are seeing? Thanks

cc: @XanderStrike

**Comment by phil9909** [comment] 2020-09-10 07:54
Hi @XanderStrike @kauana, 

We reproduce the issue without cf-for-k8s (see https://github.com/gardener/gardener/issues/2811).
Currently. we suspect that it's caused by some incompatibility between envoy and the AWS ELB.
For now there is nothing to do on your side, maybe we find some setting that you could tweak to prevent this, but we need to investigate first.

Thanks

**Comment by kauana** [comment] 2020-09-10 17:06
Oh, I see. Thanks for letting us know.

**Closed** 2020-09-10 17:09 UTC
Labels: unscheduled
