### ISSUE TITLE
Cannot view metrics with the cf7 cli

### ISSUE THREAD

**Issue by zrob** [cloudfoundry/cf-for-k8s#122] opened 2020-04-06 16:22 UTC
Currently both `cf7 push` and `cf7 apps` fail with the same error message.

```
Stats unavailable: Stats server temporarily unavailable.
FAILED
```

Both of these commands ran successfully at checksum `a7f8bbf`

**Comment by hev** [comment] 2020-04-07 17:05
I was not able to reproduce this when I tested with cf7 and included #92

**Comment by zankich** [comment] 2020-04-14 19:47
This is probably related to https://github.com/cloudfoundry/cf-for-k8s/issues/123#issuecomment-613641176

**Comment by Birdrock** [comment] 2020-04-15 22:41
Closing in favor of https://github.com/cloudfoundry/cf-for-k8s/issues/123#issuecomment-613641176

**Closed by Birdrock** 2020-04-15 22:41 UTC
Labels: scheduled
