### ISSUE TITLE
cf push fails with stratos console - Could not get the info for Cloud Foundry: Get https://api.95.217.134.196.nip.io/v2/info

### ISSUE THREAD

**Issue by cmoulliard** [cloudfoundry/cf-for-k8s#67] opened 2020-03-17 18:13 UTC
## Issue

`cf push` command fails to install the stratos console using the docker image on a fresh `cf-4-k8s` installation running on k8s - version `1.15.9`

```
cf push console -o splatform/stratos:stable -m 128M -k 384M
Pushing app console to org redhat.com / space demo as admin...
Getting app info...
Creating app with these attributes...
+ name:           console
+ docker image:   splatform/stratos:stable
+ disk quota:     384M
+ memory:         128M
  routes:
+   console.95.217.134.196.nip.io

Creating app console...
Mapping routes...
Failed to retrieve logs from Log Cache: Get /api/v1/info: unsupported protocol scheme ""


Staging app and tracing logs...
Failed to retrieve logs from Log Cache: Get /api/v1/info: unsupported protocol scheme ""

Failed to retrieve logs from Log Cache: Get /api/v1/info: unsupported protocol scheme ""

Failed to retrieve logs from Log Cache: Get /api/v1/info: unsupported protocol scheme ""

Failed to retrieve logs from Log Cache: Get /api/v1/info: unsupported protocol scheme ""


Waiting for app to start...
Start unsuccessful

TIP: use 'cf logs console --recent' for more information
FAILED
```

when we check the logs, then we go this error 
```
[snowdrop@k03-k116 cf-for-k8s]$ cf logs console --recent
Retrieving logs for app console in org redhat.com / space demo as admin...

Failed to retrieve logs from Log Cache: Get /api/v1/info: unsupported protocol scheme ""
FAILED
```

## Additional info

The pod created for the console is crashing
```
kc describe pod/console-demo-3d99bc874c-0 -n cf-workloads
Name:           console-demo-3d99bc874c-0
Namespace:      cf-workloads
Priority:       0
Node:           cf-k8s-control-plane/172.17.0.2
Start Time:     Tue, 17 Mar 2020 19:07:29 +0100
Labels:         cloudfoundry.org/app_guid=0f51adcc-d59c-4c90-9985-e9f733b23ed5
                cloudfoundry.org/guid=0f51adcc-d59c-4c90-9985-e9f733b23ed5
                cloudfoundry.org/process_type=web
                cloudfoundry.org/rootfs-version=v75.0.0
                cloudfoundry.org/source_type=APP
                cloudfoundry.org/version=04d95717-8192-4010-a6f1-b4fa4147638c
                controller-revision-hash=console-demo-3d99bc874c-5c69f5576
                security.istio.io/tlsMode=istio
                statefulset.kubernetes.io/pod-name=console-demo-3d99bc874c-0
Annotations:    cloudfoundry.org/application_id: 0f51adcc-d59c-4c90-9985-e9f733b23ed5
                cloudfoundry.org/application_name: console
                cloudfoundry.org/application_uris: [{"hostname":"console.95.217.134.196.nip.io","port":8080}]
                cloudfoundry.org/last_updated: 1584468449.544967
                cloudfoundry.org/org_guid: c4f7aa9b-18cf-4687-8073-719f61cc4168
                cloudfoundry.org/org_name: redhat.com
                cloudfoundry.org/original_request:
                  {"guid":"0f51adcc-d59c-4c90-9985-e9f733b23ed5","version":"04d95717-8192-4010-a6f1-b4fa4147638c","process_guid":"0f51adcc-d59c-4c90-9985-e9...
                cloudfoundry.org/process_guid: 0f51adcc-d59c-4c90-9985-e9f733b23ed5-04d95717-8192-4010-a6f1-b4fa4147638c
                cloudfoundry.org/routes: [{"hostname":"console.95.217.134.196.nip.io","port":8080}]
                cloudfoundry.org/space_guid: f148f02d-fcf3-4657-a3ea-f3f8cae530ad
                cloudfoundry.org/space_name: demo
                cloudfoundry.org/version: 04d95717-8192-4010-a6f1-b4fa4147638c
                seccomp.security.alpha.kubernetes.io/pod: runtime/default
                sidecar.istio.io/status:
                  {"version":"900cf5f40d6bd7757b3cee946766cc0d1be31c059a133ff269e4022a34cf96b2","initContainers":["istio-init"],"containers":["istio-proxy"]...
Status:         Running
IP:             10.244.0.33
IPs:            <none>
Controlled By:  StatefulSet/console-demo-3d99bc874c
Init Containers:
...
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                    From                           Message
  ----     ------     ----                   ----                           -------
  Normal   Scheduled  4m13s                  default-scheduler              Successfully assigned cf-workloads/console-demo-3d99bc874c-0 to cf-k8s-control-plane
  Normal   Pulled     4m12s                  kubelet, cf-k8s-control-plane  Container image "docker.io/istio/proxyv2:1.4.3" already present on machine
  Normal   Created    4m12s                  kubelet, cf-k8s-control-plane  Created container istio-init
  Normal   Started    4m9s                   kubelet, cf-k8s-control-plane  Started container istio-init
  Normal   Started    3m45s                  kubelet, cf-k8s-control-plane  Started container istio-proxy
  Normal   Pulled     3m45s                  kubelet, cf-k8s-control-plane  Container image "docker.io/istio/proxyv2:1.4.3" already present on machine
  Normal   Created    3m45s                  kubelet, cf-k8s-control-plane  Created container istio-proxy
  Normal   Started    3m18s (x3 over 3m45s)  kubelet, cf-k8s-control-plane  Started container opi
  Warning  BackOff    3m11s (x4 over 3m40s)  kubelet, cf-k8s-control-plane  Back-off restarting failed container
  Normal   Pulling    2m57s (x4 over 4m7s)   kubelet, cf-k8s-control-plane  Pulling image "splatform/stratos:stable"
  Normal   Pulled     2m56s (x4 over 3m46s)  kubelet, cf-k8s-control-plane  Successfully pulled image "splatform/stratos:stable"
  Normal   Created    2m55s (x4 over 3m46s)  kubelet, cf-k8s-control-plane  Created container opi
```

Log of the pod reports this error
```
kc logs pod/console-demo-3d99bc874c-0 -c opi -n cf-workloads
time="2020-03-17T18:19:08Z" level=info msg="Loaded configuration from file: ./config.properties"
INFO[Tue Mar 17 18:19:08 UTC 2020] ========================================
INFO[Tue Mar 17 18:19:08 UTC 2020] === Stratos Jetstream Backend Server ===
INFO[Tue Mar 17 18:19:08 UTC 2020] ========================================
INFO[Tue Mar 17 18:19:08 UTC 2020]
INFO[Tue Mar 17 18:19:08 UTC 2020] Initialization started.
INFO[Tue Mar 17 18:19:08 UTC 2020] Configuration loaded.
INFO[Tue Mar 17 18:19:08 UTC 2020] Stratos Version: 3.0.0
INFO[Tue Mar 17 18:19:08 UTC 2020] HTTP client initialized.
INFO[Tue Mar 17 18:19:08 UTC 2020] Encryption key set.
INFO[Tue Mar 17 18:19:08 UTC 2020] No DB configurations defined, will use SQLite
INFO[Tue Mar 17 18:19:08 UTC 2020] SQLite Database file: console-database.db
INFO[Tue Mar 17 18:19:08 UTC 2020] Database appears to now be available.
INFO[Tue Mar 17 18:19:08 UTC 2020] Database connection pool created.
INFO[Tue Mar 17 18:19:08 UTC 2020] ========================
INFO[Tue Mar 17 18:19:08 UTC 2020] = Stratos DB Migration =
INFO[Tue Mar 17 18:19:08 UTC 2020] ========================
INFO[Tue Mar 17 18:19:08 UTC 2020] Database provider: sqlite3
INFO[Tue Mar 17 18:19:08 UTC 2020] Current 0
INFO[Tue Mar 17 18:19:08 UTC 2020] Target: 20200117152200
INFO[Tue Mar 17 18:19:08 UTC 2020] Running migrations ....
INFO[Tue Mar 17 18:19:08 UTC 2020] Running migration: 20170818120003_InitialSchema
INFO[Tue Mar 17 18:19:08 UTC 2020] Running migration: 20170818162837_SetupSchema
INFO[Tue Mar 17 18:19:08 UTC 2020] Running migration: 20170829154900_TokenDisconnected
INFO[Tue Mar 17 18:19:08 UTC 2020] Running migration: 20171108102900_AuthType
INFO[Tue Mar 17 18:19:08 UTC 2020] Running migration: 20180413135700_MetricsSchema
INFO[Tue Mar 17 18:19:08 UTC 2020] Running migration: 20180627111300_UpdateMetadata
INFO[Tue Mar 17 18:19:08 UTC 2020] Running migration: 20180703142800_SetupSchema
INFO[Tue Mar 17 18:19:08 UTC 2020] Running migration: 20180813110300_RemoveStaleTokens
INFO[Tue Mar 17 18:19:08 UTC 2020] Running migration: 20180824092600_LinkedTokens
INFO[Tue Mar 17 18:19:08 UTC 2020] Running migration: 20180831104300_SSOEndpointFlag
INFO[Tue Mar 17 18:19:08 UTC 2020] Running migration: 20180907123000_SSOSetupFlag
INFO[Tue Mar 17 18:19:08 UTC 2020] Running migration: 20181129140500_UserFavorites
INFO[Tue Mar 17 18:19:08 UTC 2020] Running migration: 20190305144600_EndpointSubtype
INFO[Tue Mar 17 18:19:08 UTC 2020] Running migration: 20190515133200_AuthEndpoint
INFO[Tue Mar 17 18:19:08 UTC 2020] Running migration: 20190522121200_LocalUsers
INFO[Tue Mar 17 18:19:08 UTC 2020] Running migration: 20190621212700_ConfigSchema
INFO[Tue Mar 17 18:19:08 UTC 2020] Running migration: 20190918092300_LocalUsersUpdates
INFO[Tue Mar 17 18:19:08 UTC 2020] Running migration: 20190930092500_LocalUsersTriggerFix
INFO[Tue Mar 17 18:19:08 UTC 2020] Running migration: 20191008121900_PrimaryKeys
INFO[Tue Mar 17 18:19:08 UTC 2020] Running migration: 20200117152200_SesssionData
INFO[Tue Mar 17 18:19:08 UTC 2020] Session Cookie Domain:
INFO[Tue Mar 17 18:19:08 UTC 2020] Creating SQLite session store
INFO[Tue Mar 17 18:19:08 UTC 2020] Session store initialized.
INFO[Tue Mar 17 18:19:08 UTC 2020] Session data store initialized.
INFO[Tue Mar 17 18:19:08 UTC 2020] Session Cookie name: console-session
INFO[Tue Mar 17 18:19:08 UTC 2020] Initialization complete.
INFO[Tue Mar 17 18:19:08 UTC 2020] Migrating setup data to config store
INFO[Tue Mar 17 18:19:08 UTC 2020] Can not migrate setup data - setup table is empty
INFO[Tue Mar 17 18:19:08 UTC 2020] Initialising plugins
INFO[Tue Mar 17 18:19:08 UTC 2020] Loaded plugin: cfapppush
INFO[Tue Mar 17 18:19:08 UTC 2020] Loaded plugin: cfappssh
INFO[Tue Mar 17 18:19:08 UTC 2020] Loaded plugin: cloudfoundry
INFO[Tue Mar 17 18:19:08 UTC 2020] Loaded plugin: cloudfoundryhosting
INFO[Tue Mar 17 18:19:08 UTC 2020] Loaded plugin: metrics
INFO[Tue Mar 17 18:19:08 UTC 2020] Loaded plugin: userinfo
INFO[Tue Mar 17 18:19:08 UTC 2020] Loaded plugin: userinvite
INFO[Tue Mar 17 18:19:08 UTC 2020] Loaded plugin: userfavorites
INFO[Tue Mar 17 18:19:08 UTC 2020] Loaded plugin: autoscaler
INFO[Tue Mar 17 18:19:08 UTC 2020] Detected that Console is deployed as a Cloud Foundry Application
INFO[Tue Mar 17 18:19:08 UTC 2020] Updated Console address to: :8080
INFO[Tue Mar 17 18:19:08 UTC 2020] CF API URL: https://api.95.217.134.196.nip.io
INFO[Tue Mar 17 18:19:08 UTC 2020] No forced override to HTTPS
INFO[Tue Mar 17 18:19:08 UTC 2020] Features requiring persistence: enabled: false
INFO[Tue Mar 17 18:19:08 UTC 2020] Using Cloud Foundry API URL: https://api.95.217.134.196.nip.io
FATA[Tue Mar 17 18:19:09 UTC 2020] Could not get the info for Cloud Foundry: Get https://api.95.217.134.196.nip.io/v2/info: read tcp 10.244.0.33:35146->95.217.134.196:443: read: connection reset by peer
```

**Comment by jenspinney** [comment] 2020-03-17 18:45
Thanks @cmoulliard!

There may be multiple different bugs here. There is definitely a bug preventing you from seeing the logs. We can sync up with the CF CLI team around that.

One thing we have seen in the past is that the CF CLI will fail and give warning messages, but the app is actually running and curl-able on the backend. I don't think that's the case in your situation, but it would be helpful to confirm what the state of your app container in the `cf-workloads` namespace is.

Could you please provide the following extra info:
* Can you curl your app successfully? e.g., `curl console.95.217.134.196.nip.io`
* Do you see an error message in the associated pod in the `cf-workloads` namespace in kubernetes? Or does the pod appear healthy?
* What do you see when you run `cf curl /` ?

Thanks again!
Jen & @ericpromislow

**Comment by cmoulliard** [comment] 2020-03-17 20:02
> * Can you curl your app successfully? e.g., `curl console.95.217.134.196.nip.io`

As the pod is crashing and not started, then application is not running and cannot be curled.

**Comment by cmoulliard** [comment] 2020-03-17 20:03
> * Do you see an error message in the associated pod in the `cf-workloads` namespace in kubernetes? Or does the pod appear healthy?

Error is attached to my ticket - see description. I added it again hereafter
```
FATA[Tue Mar 17 18:19:09 UTC 2020] Could not get the info for Cloud Foundry: Get https://api.95.217.134.196.nip.io/v2/info: read tcp 10.244.0.33:35146->95.217.134.196:443: read: connection reset by peer
```

**Comment by jenspinney** [comment] 2020-03-17 23:19
Thanks for the extra details!

For others reviewing this later, I think these are the key logs:
```
INFO[Tue Mar 17 18:19:08 UTC 2020] Detected that Console is deployed as a Cloud Foundry Application
INFO[Tue Mar 17 18:19:08 UTC 2020] Updated Console address to: :8080
INFO[Tue Mar 17 18:19:08 UTC 2020] CF API URL: https://api.95.217.134.196.nip.io
INFO[Tue Mar 17 18:19:08 UTC 2020] No forced override to HTTPS
INFO[Tue Mar 17 18:19:08 UTC 2020] Features requiring persistence: enabled: false
INFO[Tue Mar 17 18:19:08 UTC 2020] Using Cloud Foundry API URL: https://api.95.217.134.196.nip.io
FATA[Tue Mar 17 18:19:09 UTC 2020] Could not get the info for Cloud Foundry: Get https://api.95.217.134.196.nip.io/v2/info: read tcp 10.244.0.33:35146->95.217.134.196:443: read: connection reset by peer
```

I wonder if the problem here could be that the Stratos container doesn't trust the CA that signed the CF system's server certificate. To confirm or rule out that guess, you could try setting Stratos' CF API URL explicitly to use `http` instead of `https`:

```
cf set-env CF_API_URL http://api.95.217.134.196.nip.io
cf restart console
```

**Comment by cmoulliard** [comment] 2020-03-18 07:37
Many thanks @jenspinney for your help. I chanaged the protocol from HTTPS to HTTP as you proposed 

```
cf set-env console CF_API_URL http://api.95.217.134.196.nip.io
cf restage console
cf logs console --recent
```

and now we got an error 503
```
INFO[Wed Mar 18 07:35:06 UTC 2020] CF API URL: https://api.95.217.134.196.nip.io
INFO[Wed Mar 18 07:35:06 UTC 2020] Overriden CF API URL from environment variable http://api.95.217.134.196.nip.io
INFO[Wed Mar 18 07:35:06 UTC 2020] No forced override to HTTPS
INFO[Wed Mar 18 07:35:06 UTC 2020] Features requiring persistence: enabled: false
INFO[Wed Mar 18 07:35:06 UTC 2020] Using Cloud Foundry API URL: http://api.95.217.134.196.nip.io
DEBU[Wed Mar 18 07:35:06 UTC 2020] Info
FATA[Wed Mar 18 07:35:07 UTC 2020] Could not get the info for Cloud Foundry: 
http://api.95.217.134.196.nip.io/v2/info 
endpoint returned 503
upstream connect error or disconnect/reset before headers. reset reason: connection failure
```

**Comment by tcdowney** [comment] 2020-03-18 22:15
The `Statsd` logs seem like a red-herring. I think that is Cloud Controller failing to send metrics to a statsd agent that probably doesn't exist. I can actually hit your API server from my local workstation which is interesting...

```
curl http://api.95.217.134.196.nip.io/v2/info
{"name":"","build":"","support":"","version":0,"description":"","authorization_endpoint":"https://login.95.217.134.196.nip.io","token_endpoint":"https://uaa.95.217.134.196.nip.io","min_cli_version":"","min_recommended_cli_version":"","app_ssh_endpoint":"TODO.TODO","app_ssh_host_key_fingerprint":"placeholder","app_ssh_oauth_client":"placeholder","doppler_logging_endpoint":"wss://doppler.95.217.134.196.nip.io:443","api_version":"2.147.0","osbapi_version":"2.15","routing_endpoint":"https://api.95.217.134.196.nip.io/routing"}
```

Can you `kubectl -n cf-workloads <stratos-pod-name> exec -it /bin/bash` (or equivalent) and try curling it from within the pod with the `-v` flag. I have a feeling it's probably blocked, but it is a useful debugging step.

I wonder if this config that we added to block inter-app traffic by default within `cf-workloads` is causing any issues.
https://github.com/cloudfoundry/cf-for-k8s/blob/6df235e471906de7e09b8f6aa576ea6206d67432/config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/istio-generated/xxx-generated-istio.yaml#L6212-L6223

**Comment by ericpromislow** [comment] 2020-03-18 22:57
Tim, we're currently resource-constrained because we don't have a good machine to ssh to right now. Can you write an app and cf4k8s-deploy it that curls http://api.95.217.134.196.nip.io/v2/info ?

**Comment by cmoulliard** [comment] 2020-03-19 08:29
> Can you `kubectl -n cf-workloads <stratos-pod-name> exec -it /bin/bash` (or equivalent) and try curling it from within the pod with the `-v` flag. I have a feeling it's probably blocked, but it is a useful debugging step.

There is a routing istio issue
```
[snowdrop@k03-k116 ~]$ kn exec pod/console-demo-b81ef505d6-0 -it /bin/bash -c istio-proxy
istio-proxy@console-demo-b81ef505d6-0:/$ curl http://api.95.217.134.196.nip.io/v2/info
curl: (7) Failed to connect to api.95.217.134.196.nip.io port 80: No route to host
istio-proxy@console-demo-b81ef505d6-0:/$ curl -v curl http://api.95.217.134.196.nip.io/v2/info
* Rebuilt URL to: curl/
* Could not resolve host: curl
* Closing connection 0
curl: (6) Could not resolve host: curl
*   Trying 95.217.134.196...
* TCP_NODELAY set
* connect to 95.217.134.196 port 80 failed: No route to host
* Failed to connect to api.95.217.134.196.nip.io port 80: No route to host
* Closing connection 1
curl: (7) Failed to connect to api.95.217.134.196.nip.io port 80: No route to host
```

**Comment by cmoulliard** [comment] 2020-03-19 08:33
> It may be helpful to also check the logs on the `istio-ingressgateway` in `istio-system` to see if it says anything.

here is the full log : https://gist.githubusercontent.com/cmoulliard/9785af087672dd375308adef7521a76f/raw/50f66b8be94a530f00a21e0269a9f9b4c3811169/gistfile1.txt

**Comment by tcdowney** [comment] 2020-03-19 16:18
In the example above your curl command looks malformed, there is an extra `curl` in there which is confusing it.

```
curl -v curl http://api.95.217.134.196.nip.io/v2/info
```

Should be:
```
curl -v http://api.95.217.134.196.nip.io/v2/info
```

**Comment by cmoulliard** [comment] 2020-03-19 16:39
> Should be:

I executed the command again
```
curl -v http://api.95.217.134.196.nip.io/v2/info
*   Trying 95.217.134.196...
* TCP_NODELAY set
* connect to 95.217.134.196 port 80 failed: No route to host
* Failed to connect to api.95.217.134.196.nip.io port 80: No route to host
* Closing connection 0
curl: (7) Failed to connect to api.95.217.134.196.nip.io port 80: No route to host
```

**Comment by tcdowney** [comment] 2020-03-19 17:58
Ask @cmoulliard can you hit any external address? E.g. `https://google.com`? That error you're getting looks like a Layer 2 problem potentially.. I don't think the `NetworkPolicy` we have in place should be doing this (it's not in our env).

**Comment by cmoulliard** [comment] 2020-03-19 18:01
I can 
```
curl https://www.pivotal.com
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
</body>
</html>
istio-proxy@console-demo-b81ef505d6-0:/$
```

**Comment by jenspinney** [comment] 2020-03-23 23:03
We tried to reproduce this ourselves by deploying Stratos on cf-for-k8s (using [these instructions]( https://github.com/cloudfoundry/stratos/tree/30216eb5194d85a83d5c98aef942f2c22fcaec0d/deploy/cloud-foundry#Deploy-Stratos-from-docker-image)). Our cf-for-k8s test cluster is running on GKE, Kubernetes version v1.15.9-gke.22.

We observed something a little different, but also non-functional. We were able to push the app successfully, but `curl`-ing didn't work. When we attempted to reach our app over port 80 (i.e., `http`), we got back a `301 Moved Permanently` response. The redirect pointed us to the `https` version of the app. But because we don't yet support port 443 (https) access to apps, we got a `404` response to that request.

We found that the HTTPS redirect was happening in the [stratos application itself]( https://github.com/cloudfoundry/stratos/blob/f9437f41d08c5ca6169381de8f3c510529d622aa/src/jetstream/plugins/cloudfoundryhosting/main.go#L255-L269) and not one of the networking pieces deployed as part of cf-for-k8s.

Unless stratos has an option to skip that redirect, we expect it not to work due to our known issue https://github.com/cloudfoundry/cf-for-k8s/issues/46.

**Comment by jenspinney** [comment] 2020-03-23 23:30
@cmoulliard we're not sure how to help with the "No route to host" error. From our attempts at repro-ing, we aren't seeing the same thing, so we're inclined to think it's something about the IaaS-level networking configuration in your environment.

If you think there are other steps we can try to repro this, please feel free to re-open, but we'll close this now as no-repro and stratos-wont-work-for-now-anyway.

Thanks,
Jen & @jamespollard8

**Closed by jenspinney** 2020-03-23 23:30 UTC
Labels: in progress
