### ISSUE TITLE
Spring apps pushed to cf-for-k8s are unreachable, even via http

### ISSUE THREAD

**Issue by andrewedstrom** [cloudfoundry/cf-for-k8s#153] opened 2020-04-17 22:18 UTC
### Summary

We are having issues deploying a hello world spring app to cf-for-k8s. We cf pushed [this app](https://github.com/cloudfoundry-samples/cf-sample-app-spring) and the push succeeds, but afterwards the app is not reachable.

When we try to connect with http we see this error: `upstream connect error or disconnect/reset before headers. reset reason: connection failure`

We saw the same error when we tried to push our team's spring boot application to cf-for-k8s.

### Reproduction Steps
https://github.com/cloudfoundry/cf-for-k8s/tree/bb1b88a0c22eb265378258b0f0a65eead00b94de

We used `bin/install-cf.sh` to deploy it with installation values generated by ./hack/generate-values.sh

IaaS name(s): GKE. 
Kubernetes version: v1.14.10-gke.27

_What steps/actions led to the issue?_
```
git clone https://github.com/cloudfoundry-samples/cf-sample-app-spring
cd cf-sample-app-spring
cf push
```

Kubectl says the app is running, and the Istio container is healthy.
```
→ kc get pods -n cf-workloads
NAME                                                    READY   STATUS    RESTARTS   AGE
cf-demo-test-space-44d79159ff-0                         2/2     Running   0      
```

CF says the app status is “started”:
```
→ cf apps
Getting apps in org test-org / space test-space as sso-temp-cf-client...
OK
name            requested state   instances   memory   disk   urls
test-node-app   started           1/1         1G       1G     test-node-app.cf4k8s.sso.identity.team
cf-demo         started           1/1         768M     1G     cf-demo-noisy-civet-mx.cf4k8s.sso.identity.team
```

### Expected behavior

When we try to visit the app's url we should see the hello world page.

**Comment by drnic** [comment] 2020-04-17 22:20
As a data point, I ran spring-music successfully.

**Comment by davewalter** [comment] 2020-04-20 18:05
Closing in favour of [this discussion in Slack](https://cloudfoundry.slack.com/archives/CH9LF6V1P/p1587158476429800?thread_ts=1587157742.429700&cid=CH9LF6V1P) since we suspect that the issue is specific to your installation. Please feel free to reopen the issue (or continue to reach out in Slack) if you can determine the steps to reproduce the problem.

Thanks,
Dave and @jamespollard8

**Closed by davewalter** 2020-04-20 18:05 UTC
Labels: unscheduled
