### ISSUE TITLE
/v2/resource_match returns status code 413 for large nodejs app

### ISSUE THREAD

**Issue by nrekretep** [cloudfoundry/cf-for-k8s#260] opened 2020-06-28 07:57 UTC
## Describe the bug
I am trying to `cf push` a nodejs app to cf for k8s. 
The node_modules are included in the deployment. In the `node_modules` directory there are 99198 files. 

`cf push` stops the deployment of the app with the error message 

```
FAILED
Error processing app files: Error uploading application.
Server error, status code: 413, error code: 0, message:
```

## To Reproduce*
```
$ cf push -f manifest.yml -v
...
Using route console.apps.system.local-cf.org
Uploading console...

REQUEST: [2020-06-28T09:16:20+02:00]
PUT /v2/resource_match HTTP/1.1
Host: api.system.local-cf.org
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.51.0+2acd15650.2020-04-07 / linux

[
  {
    "sha1": "5b5c5fc7e80de17f54a5eee4a4ff383c7c094ab1",
    "size": 336
  },
  {
    "sha1": "3735c653cd1232359d44e8c265c6e1867188ed2a",
    "size": 452
  },
  {
    "sha1": "8e59e6642f635c0990307e7ab9be2292bc5caf84",
    "size": 353
  },
...
]

RESPONSE: [2020-06-28T09:16:21+02:00]
HTTP/1.1 413 Payload Too Large^M
Connection: close^M
Content-Length: 176^M
Content-Type: text/html^M
Date: Sun, 28 Jun 2020 07:16:21 GMT^M
Server: istio-envoy^M
^M
<html>^M
<head><title>413 Request Entity Too Large</title></head>^M
<body>^M
<center><h1>413 Request Entity Too Large</h1></center>^M
<hr><center>nginx</center>^M
</body>^M
</html>^M
 
FAILED
Error processing app files: Error uploading application.
Server error, status code: 413, error code: 0, message:
```

## Expected behavior

If there are too many files to check against `/v2/resource_match` I would expect that the deployment would either 
* continue to successfully deploy the app (maybe with some kind of warning that the deployment now takes a little bit longer because of skipping the resource_match step)
or
* it stops the deployment and the error message provides a hint for correcting the error or working around the error. 

### cf-for-k8s SHA 
[6482fa75155f3ab8f373da1754b244b6cf439e3d](https://github.com/cloudfoundry/cf-for-k8s/commit/6482fa75155f3ab8f373da1754b244b6cf439e3d)

### Cluster information
Local k8s cluster with kvm/libvirt on Fedora linux. 

### Version of ytt

```
$ ytt version                                                 
ytt version 0.27.2
```

### Version of kapp

```
$ kapp version       
kapp version 0.27.0

Succeeded
```

### Version of kubectl

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

### Version of cf cli

```
$ cf version
cf version 6.51.0+2acd15650.2020-04-07
```

### Version of cf 
```
$ cf curl /v2/info                            
{
   "name": "",
   "build": "",
   "support": "",
   "version": 0,
   "description": "",
   "authorization_endpoint": "https://login.system.local-cf.org",
   "token_endpoint": "https://uaa.system.local-cf.org",
   "min_cli_version": "",
   "min_recommended_cli_version": "",
   "app_ssh_endpoint": "TODO.TODO",
   "app_ssh_host_key_fingerprint": "placeholder",
   "app_ssh_oauth_client": "placeholder",
   "doppler_logging_endpoint": "wss://doppler.system.local-cf.org:443",
   "api_version": "2.150.0",
   "osbapi_version": "2.15",
   "routing_endpoint": "https://api.system.local-cf.org/routing",
   "user": "d50af615-9719-414a-a576-c9b6685ca7c1"
}
```

**Comment by ndhanushkodi** [comment] 2020-07-23 22:35
Do you know how large the app/payload is @nrekretep? I've been trying to reproduce by sending files (1Mb, 100Mb, and 1Gb) over a request through the ingress envoy and they have all succeeded so I'm not able to reproduce.

**Comment by keshav-pivotal** [comment] 2020-10-08 22:46
Closing this issue since we were unable to reproduce the issue.

**Closed** 2020-10-08 22:45 UTC
Labels: known-issue, unscheduled
